### ISSUE TITLE
Python 3 build failure since https://github.com/mozilla/clouseau/pull/96

### ISSUE THREAD

**Issue by marco-c** [mozilla/clouseau#98]
```
libmozdata>=0.1.17->-r requirements.txt (line 1))
Collecting mercurial>=3.9.1 (from libmozdata>=0.1.17->-r requirements.txt (line 1))
  Downloading mercurial-4.0.0.tar.gz (4.9MB)
    100% |████████████████████████████████| 4.9MB 315kB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/setuptools/dist.py:340: UserWarning: The version specified (b'4.0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ftpa_l8w/mercurial/setup.py", line 720, in <module>
        **extra)
      File "/opt/python/3.5.2/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/python/3.5.2/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/python/3.5.2/lib/python3.5/distutils/dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "/opt/python/3.5.2/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 174, in finalize_options
        self.egg_version = self.tagged_version()
      File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 264, in tagged_version
        return safe_version(version + self.vtags)
    TypeError: can't concat bytes to str
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ftpa_l8w/mercurial/
```

**Comment by marco-c** [comment]
I guess we need to update `pip` and `setuptools`.

**Comment by marco-c** [comment]
Oh, we already are, so that's not what it is.

**Comment by marco-c** [comment]
It's working again now.
